# Generated by Django 2.2.6 on 2019-11-06 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_attendant'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendants',
            field=models.ManyToManyField(to='main_app.Attendant'),
        ),
    ]
