# Generated by Django 2.2.6 on 2019-11-06 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_event_attendants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendant',
            name='id',
        ),
        migrations.AlterField(
            model_name='attendant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
