# Generated by Django 2.2.6 on 2019-11-07 16:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20191106_2041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendant',
            old_name='confirmations',
            new_name='confirmation',
        ),
        migrations.AddField(
            model_name='attendant',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='confirmation date'),
            preserve_default=False,
        ),
    ]
