# Generated by Django 2.2.6 on 2019-11-07 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20191106_2041'),
        ('main_app', '0004_auto_20191107_1858'),
    ]

    operations = [
    ]
