# Generated by Django 2.2.6 on 2019-11-07 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20191107_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='attendants',
        ),
        migrations.AddField(
            model_name='attendant',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Event'),
            preserve_default=False,
        ),
    ]
