# Generated by Django 2.2.6 on 2019-11-07 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20191107_2033'),
        ('main_app', '0005_merge_20191107_1937'),
    ]

    operations = [
    ]
